name: admin_app
description: "A Admin Console to manage app cfe_cgc_af."
publish_to: 'none'

version: 1.0.0+2002R

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  # IcÃ´nes iOS style Cupertino
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.10.1

  # ğŸ”” Notifications locales (multi-plateforme)
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter

  # Pour ouvrir des liens (utile dans beaucoup dâ€™apps admin)
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  intl: ^0.20.2
  file_picker: ^10.3.3
  pdfx: ^2.9.2
  path: ^1.9.1
  webview_flutter: ^4.13.0
  uuid: ^4.5.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints recommandÃ©s
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # DÃ©commente si tu ajoutes des images ou ressources
  # assets:
  #   - assets/images/
